export const metadata = {
  title: '{{PROJECT_NAME}}',
  description: 'Generated by program-starter',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
